/* Casos de test del Level 3 de ESTA app (Relative Clauses).
   full: respuesta modelo SIN contracciones (de ella salen las variantes contraídas)
   pos:  variantes que deben ACEPTARSE · neg: respuestas incorrectas que deben FALLAR */
module.exports = {
  /* ---------- 1 · Relative Pronouns ---------- */
  rp_l3_0: { full: "The girl who lives next door is my cousin.",
    pos: ["The girl that lives next door is my cousin", "the girl who lives next door is my cousin!"],
    neg: ["The girl which lives next door is my cousin.", "The girl lives next door is my cousin.", "The girl who she lives next door is my cousin.",
          "The girl whose lives next door is my cousin.", "The girl who live next door is my cousin.", "The girl what lives next door is my cousin.",
          "The girl who lives next door are my cousin."] },
  rp_l3_1: { full: "This is the village where my father was born.",
    pos: ["This is the town where my dad was born.", "This is the village in which my father was born.", "This is the village my father was born in.",
          "This is the village that my dad was born in."],
    neg: ["This is the village which my father was born.", "This is the village where my father was born in.", "This is the village who my father was born.",
          "This is the village where my father born.", "This is the village where was born my father.", "This is the village when my father was born.",
          "This is the village that my father was born."] },
  rp_l3_2: { full: "I have a friend whose father is a pilot.",
    pos: ["I've got a friend whose dad is a pilot.", "I have got a friend whose father is a pilot"],
    neg: ["I have a friend who his father is a pilot.", "I have a friend who's father is a pilot.", "I have a friend which father is a pilot.",
          "I have a friend whose his father is a pilot.", "I have a friend that father is a pilot.", "I have a friend whose father is pilot.",
          "I have a friend whose the father is a pilot."] },
  rp_l3_3: { full: "I remember the day when we met.",
    pos: ["I remember the day we met.", "I remember the day that we met", "I remember the day on which we met.", "I remember the day when we first met."],
    neg: ["I remember the day where we met.", "I remember the day which we met.", "I remember the day who we met.", "I remember the day when we meet.",
          "I remember the day when we met us.", "I remember the day what we met.", "I remember the day in which we met."] },
  rp_l3_4: { full: "The book that I am reading is very interesting.",
    pos: ["The book I'm reading is really interesting.", "The book which I am reading is very interesting.", "The book Im reading is very interesting"],
    neg: ["The book who I am reading is very interesting.", "The book that I am reading it is very interesting.", "The book what I am reading is very interesting.",
          "The book where I am reading is very interesting.", "The book that I reading is very interesting.", "The book that I am reading is very interested.",
          "The book whose I am reading is very interesting."] },
  rp_l3_5: { full: "Is that the boy who won the race?",
    pos: ["Is that the boy that won the race?", "is that the boy who won the race"],
    neg: ["Is that the boy which won the race?", "Is that the boy won the race?", "Is that the boy who he won the race?", "Is that the boy who did win the race?",
          "Is that the boy whose won the race?", "That is the boy who won the race?", "Is that the boy who win the race?"] },
  rp_l3_6: { full: "Do you know anyone who speaks Japanese?",
    pos: ["Do you know anybody that speaks Japanese?", "Do you know someone who speaks Japanese?", "Do you know somebody who speaks japanese"],
    neg: ["Do you know anyone which speaks Japanese?", "Do you know anyone speaks Japanese?", "Do you know anyone who speak Japanese?",
          "Do you know anyone who does speak Japanese?", "Do you know anyone whose speaks Japanese?", "You know anyone who speaks Japanese?",
          "Do you know anyone who speaks Japan?"] },
  rp_l3_7: { full: "Where is the shop where you bought those shoes?",
    pos: ["Where's the shop you bought those shoes in?", "Where is the store where you bought those shoes?", "Where is the shop in which you bought those shoes?",
          "Where's the shop that you bought those shoes at?"],
    neg: ["Where is the shop which you bought those shoes?", "Where is the shop where you bought those shoes in?", "Where is the shop who you bought those shoes?",
          "Where is the shop where you bought these shoes?", "Where is the shop where did you buy those shoes?", "Where is the shop where you buyed those shoes?",
          "Where the shop is where you bought those shoes?"] },
  rp_l3_8: { full: "I do not like people who lie.",
    pos: ["I don't like people that lie.", "I don't like people who tell lies.", "I dont like people who lie"],
    neg: ["I don't like people which lie.", "I don't like people lie.", "I don't like people who lies.", "I don't like people who they lie.",
          "I don't like the people what lie.", "I no like people who lie.", "I doesn't like people who lie."] },
  rp_l3_9: { full: "I did not understand what he said.",
    pos: ["I didn't understand what she said.", "I didnt understand what he said"],
    neg: ["I didn't understand that he said.", "I didn't understand which he said.", "I didn't understand what said.", "I didn't understood what he said.",
          "I didn't understand the what he said.", "I don't understand what he said.", "I didn't understand what he say."] },

  /* ---------- 2 · Defining ---------- */
  def_l3_0: { full: "The man who fixed my bike is very kind.",
    pos: ["The man that repaired my bicycle is very nice.", "The man who mended my bike is really friendly."],
    neg: ["The man which fixed my bike is very kind.", "The man fixed my bike is very kind.", "The man, whose fixed my bike, is very kind.",
          "The man who he fixed my bike is very kind.", "The man who fix my bike is very kind.", "The man who fixed my bike are very kind.",
          "The man what fixed my bike is very kind."] },
  def_l3_1: { full: "The film we saw last night was very funny.",
    pos: ["The movie that we watched last night was really funny.", "The film which we saw last night was very entertaining.", "The film we saw last night was very fun."],
    neg: ["The film who we saw last night was very funny.", "The film we saw it last night was very funny.", "The film what we saw last night was very funny.",
          "The film where we saw last night was very funny.", "The film we see last night was very funny.", "The film we saw last night is very funny.",
          "The film we saw last night was very funnily."] },
  def_l3_2: { full: "The students who study hard pass the exam.",
    pos: ["Students that study a lot pass the exam.", "The students who study hard pass the test."],
    neg: ["The students which study hard pass the exam.", "The students study hard pass the exam.", "The students who studies hard pass the exam.",
          "The students who study hard passes the exam.", "The students who they study hard pass the exam.", "The students whose study hard pass the exam.",
          "The students who study hardly pass the exam."] },
  def_l3_3: { full: "That is the girl whose brother plays basketball.",
    pos: ["That's the girl whose brother plays basketball.", "Thats the girl whose brother plays basketball"],
    neg: ["That is the girl who her brother plays basketball.", "That is the girl who's brother plays basketball.", "That is the girl which brother plays basketball.",
          "That is the girl whose brother play basketball.", "That is the girl whose brother plays the basketball.", "That is the girl that brother plays basketball.",
          "That is the girl whose her brother plays basketball."] },
  def_l3_4: { full: "The present you gave me is beautiful.",
    pos: ["The gift that you gave me is lovely.", "The present which you gave me is beautiful.", "The gift you gave me is gorgeous."],
    neg: ["The present who you gave me is beautiful.", "The present you gave me it is beautiful.", "The present what you gave me is beautiful.",
          "The present you give me is beautiful.", "The present you gave me are beautiful.", "The present you gave to me it is beautiful.",
          "The present where you gave me is beautiful."] },
  def_l3_5: { full: "Have you seen the keys that were on the table?",
    pos: ["Have you seen the keys which were on the table?", "Did you see the keys that were on the table?"],
    neg: ["Have you seen the keys who were on the table?", "Have you seen the keys were on the table?", "Have you seen the keys that was on the table?",
          "Have you seen the keys that they were on the table?", "Have you saw the keys that were on the table?", "Have you seen the keys what were on the table?",
          "Did you saw the keys that were on the table?"] },
  def_l3_6: { full: "Who is the woman who is talking to your mother?",
    pos: ["Who's the woman that is talking to your mum?", "Who is the woman who's talking with your mother?", "Who is the woman that's speaking to your mom?"],
    neg: ["Who is the woman which is talking to your mother?", "Who is the woman is talking to your mother?", "Who is the woman who talking to your mother?",
          "Who is the woman who she is talking to your mother?", "Who is the woman whose is talking to your mother?", "Who is the woman who are talking to your mother?",
          "Who the woman is who is talking to your mother?"] },
  def_l3_7: { full: "Did you like the book I lent you?",
    pos: ["Did you like the book that I lent you?", "Did you like the book which I lent you?"],
    neg: ["Did you like the book who I lent you?", "Did you like the book I lent it you?", "Did you like the book what I lent you?", "Did you liked the book I lent you?",
          "Did you like the book I lend you?", "Do you liked the book I lent you?", "Did you like the book whose I lent you?"] },
  def_l3_8: { full: "I can not find the pen you gave me.",
    pos: ["I can't find the pen that you gave me.", "I cannot find the pen which you gave me.", "I cant find the pen you gave me"],
    neg: ["I can't find the pen who you gave me.", "I can't find the pen you gave me it.", "I can't find the pen what you gave me.", "I can't find the pen you give me.",
          "I can't found the pen you gave me.", "I don't can find the pen you gave me.", "I can't find the pen where you gave me."] },
  def_l3_9: { full: "I do not know anyone who lives in London.",
    pos: ["I don't know anybody that lives in London.", "I know nobody who lives in London.", "I know no one who lives in London."],
    neg: ["I don't know anyone which lives in London.", "I don't know anyone lives in London.", "I don't know nobody who lives in London.",
          "I don't know anyone who live in London.", "I don't know anyone who lives on London.", "I don't know anyone whose lives in London.",
          "I not know anyone who lives in London."] },

  /* ---------- 3 · Non-defining ---------- */
  nd_l3_0: { full: "My brother, who lives in London, is a doctor.",
    pos: ["My brother who lives in London is a doctor", "My brother,who lives in London,is a doctor."],
    neg: ["My brother, that lives in London, is a doctor.", "My brother, lives in London, is a doctor.", "My brother, which lives in London, is a doctor.",
          "My brother, who he lives in London, is a doctor.", "My brother, who lives in London, is doctor.", "My brother, who live in London, is a doctor.",
          "My brother, whose lives in London, is a doctor."] },
  nd_l3_1: { full: "Huesca, which is in Aragon, is a quiet city.",
    pos: ["Huesca, which is in Aragón, is a peaceful city.", "Huesca, which is in Aragon, is a calm town."],
    neg: ["Huesca, that is in Aragon, is a quiet city.", "Huesca, is in Aragon, is a quiet city.", "Huesca, where is in Aragon, is a quiet city.",
          "Huesca, who is in Aragon, is a quiet city.", "Huesca, which it is in Aragon, is a quiet city.", "Huesca, which is in Aragon, is a quite city.",
          "Huesca, which is on Aragon, is a quiet city."] },
  nd_l3_2: { full: "My teacher, whose husband is English, speaks English very well.",
    pos: ["My teacher, whose husband is English, speaks very good English."],
    neg: ["My teacher, who her husband is English, speaks English very well.", "My teacher, who's husband is English, speaks English very well.",
          "My teacher, that husband is English, speaks English very well.", "My teacher, whose husband is English, speaks very well English.",
          "My teacher, whose husband is English, speak English very well.", "My teacher, which husband is English, speaks English very well.",
          "My teacher, whose husband is England, speaks English very well."] },
  nd_l3_3: { full: "I passed all my exams, which surprised my parents.",
    pos: ["I passed all the exams, which surprised my parents.", "I passed all of my exams, which surprised my parents.", "I passed all my tests, which surprised my parents."],
    neg: ["I passed all my exams, what surprised my parents.", "I passed all my exams, that surprised my parents.", "I passed all my exams, who surprised my parents.",
          "I passed all my exams, which it surprised my parents.", "I passed all my exams, which surprise my parents.", "I approved all my exams, which surprised my parents.",
          "I passed all my exams, which surprised to my parents."] },
  nd_l3_4: { full: "Picasso, who was born in Malaga, painted Guernica.",
    pos: ["Picasso, who was born in Málaga, painted the Guernica."],
    neg: ["Picasso, that was born in Malaga, painted Guernica.", "Picasso, which was born in Malaga, painted Guernica.", "Picasso, was born in Malaga, painted Guernica.",
          "Picasso, who born in Malaga, painted Guernica.", "Picasso, who was born on Malaga, painted Guernica.", "Picasso, who was born in Malaga, paint Guernica.",
          "Picasso, who is born in Malaga, painted Guernica."] },
  nd_l3_5: { full: "Do you know Marta, who works with my father?",
    pos: ["Do you know Marta, who works with my dad?"],
    neg: ["Do you know Marta, that works with my father?", "Do you know Marta, which works with my father?", "Do you know Marta, works with my father?",
          "Do you know Marta, who work with my father?", "Do you know to Marta, who works with my father?", "You know Marta, who works with my father?",
          "Do you know Marta, whose works with my father?"] },
  nd_l3_6: { full: "Have you been to Jaca, where my grandmother lives?",
    pos: ["Have you ever been to Jaca, where my grandma lives?", "Have you visited Jaca, where my grandmother lives?", "Have you been to Jaca, in which my granny lives?"],
    neg: ["Have you been to Jaca, which my grandmother lives?", "Have you been to Jaca, that my grandmother lives?", "Have you been to Jaca, where my grandmother lives there?",
          "Have you visited to Jaca, where my grandmother lives?", "Have you been to Jaca, where my grandmother live?", "Have you been to Jaca, when my grandmother lives?",
          "Have you been to Jaca, where lives my grandmother?"] },
  nd_l3_7: { full: "Why did you sell your car, which was almost new?",
    pos: ["Why did you sell your car, which was nearly new?"],
    neg: ["Why did you sell your car, that was almost new?", "Why did you sell your car, who was almost new?", "Why did you sell your car, was almost new?",
          "Why did you sold your car, which was almost new?", "Why you sold your car, which was almost new?", "Why did you sell your car, which it was almost new?",
          "Why did you sell your car, which is almost new?"] },
  nd_l3_8: { full: "My grandfather, who is 80, does not use a mobile phone.",
    pos: ["My grandad, who is 80 years old, doesn't use his mobile.", "My grandfather, who is eighty, does not use a phone.", "My grandpa, who is 80, never uses a smartphone."],
    neg: ["My grandfather, that is 80, doesn't use a mobile phone.", "My grandfather, who has 80 years, doesn't use a mobile phone.",
          "My grandfather, which is 80, doesn't use a mobile phone.", "My grandfather, who is 80, don't use a mobile phone.",
          "My grandfather, who is 80, doesn't uses a mobile phone.", "My grandfather, is 80, doesn't use a mobile phone.", "My grandfather, who is 80, not use a mobile phone."] },
  nd_l3_9: { full: "My mobile, which I bought last month, does not work.",
    pos: ["My phone, which I bought last month, isn't working.", "My mobile phone, which I bought last month, doesn't work."],
    neg: ["My mobile, that I bought last month, doesn't work.", "My mobile, I bought last month, doesn't work.", "My mobile, which I bought it last month, doesn't work.",
          "My mobile, which I bought last month, don't work.", "My mobile, what I bought last month, doesn't work.", "My mobile, which I buy last month, doesn't work.",
          "My mobile, which I bought the last month, doesn't work."] },

  /* ---------- 4 · Defining vs Non-defining ---------- */
  dnd_l3_0: { full: "The boy I like is called Leo.",
    pos: ["The boy who I like is called Leo.", "The boy that I like is named Leo.", "The boy whom I like is called Leo."],
    neg: ["The boy which I like is called Leo.", "The boy I like him is called Leo.", "The boy what I like is called Leo.", "The boy I like calls Leo.",
          "The boy I like is call Leo.", "The boy I like he is called Leo.", "The boy whose I like is called Leo."] },
  dnd_l3_1: { full: "My mother, who is a nurse, works at night.",
    pos: ["My mum, who is a nurse, works nights.", "My mother, who is a nurse, works night shifts."],
    neg: ["My mother, that is a nurse, works at night.", "My mother, is a nurse, works at night.", "My mother, which is a nurse, works at night.",
          "My mother, who is nurse, works at night.", "My mother, who is a nurse, work at night.", "My mother, who is a nurse, works in the night.",
          "My mother, who she is a nurse, works at night."] },
  dnd_l3_2: { full: "The restaurant where we had dinner was very expensive.",
    pos: ["The restaurant we had dinner at was really expensive.", "The restaurant where we ate was very expensive.", "The restaurant in which we had dinner was very expensive."],
    neg: ["The restaurant which we had dinner was very expensive.", "The restaurant where we had dinner at was very expensive.", "The restaurant who we had dinner was very expensive.",
          "The restaurant where we had dinner were very expensive.", "The restaurant where we have dinner was very expensive.", "The restaurant when we had dinner was very expensive.",
          "The restaurant where we had dinner it was very expensive."] },
  dnd_l3_3: { full: "Valencia, where my aunt lives, has beautiful beaches.",
    pos: ["Valencia, where my aunt lives, has got lovely beaches.", "Valencia, in which my aunt lives, has wonderful beaches."],
    neg: ["Valencia, which my aunt lives, has beautiful beaches.", "Valencia, that my aunt lives, has beautiful beaches.", "Valencia, where my aunt lives, have beautiful beaches.",
          "Valencia, where lives my aunt, has beautiful beaches.", "Valencia, where my aunt live, has beautiful beaches.", "Valencia, where my aunt lives there, has beautiful beaches.",
          "Valencia, where my aunt lives, has beautifuls beaches."] },
  dnd_l3_4: { full: "He gave me a book, which was very kind.",
    pos: ["He gave me a book, which was really nice of him.", "He gave me a book, which was very kind of him."],
    neg: ["He gave me a book, what was very kind.", "He gave me a book, that was very kind.", "He gave me a book, who was very kind.", "He gave me a book, which it was very kind.",
          "He give me a book, which was very kind.", "He gave me a book, which is very kind.", "He gave me a book, which was very kindly."] },
  dnd_l3_5: { full: "Is this the bus that goes to the beach?",
    pos: ["Is this the bus which goes to the beach?"],
    neg: ["Is this the bus who goes to the beach?", "Is this the bus goes to the beach?", "Is this the bus that go to the beach?", "Is this the bus that does go to the beach?",
          "Is this the bus that goes to beach?", "This is the bus that goes to the beach?", "Is this the bus where goes to the beach?"] },
  dnd_l3_6: { full: "Have you read Don Quixote, which Cervantes wrote?",
    pos: ["Have you read Don Quixote, which was written by Cervantes?", "Have you ever read Don Quixote, which Cervantes wrote?", "Have you read El Quijote, which Cervantes wrote?"],
    neg: ["Have you read Don Quixote, that Cervantes wrote?", "Have you read Don Quixote, Cervantes wrote?", "Have you read Don Quixote, which Cervantes wrote it?",
          "Have you read Don Quixote, who Cervantes wrote?", "Have you read Don Quixote, which wrote Cervantes?", "Did you read Don Quixote, which Cervantes wrote?",
          "Have you readed Don Quixote, which Cervantes wrote?"] },
  dnd_l3_7: { full: "Do you know the man whose car is parked outside?",
    pos: ["do you know the man whose car is parked outside"],
    neg: ["Do you know the man who his car is parked outside?", "Do you know the man who's car is parked outside?", "Do you know the man which car is parked outside?",
          "Do you know the man whose car parked outside?", "Do you know the man whose car is park outside?", "Do you know the man whose his car is parked outside?",
          "Do you know the man whose car are parked outside?"] },
  dnd_l3_8: { full: "I did not like the food we ordered.",
    pos: ["I didn't like the food that we ordered.", "I didn't like the meal which we ordered."],
    neg: ["I didn't like the food who we ordered.", "I didn't like the food we ordered it.", "I didn't like the food what we ordered.", "I didn't liked the food we ordered.",
          "I don't like the food we ordered.", "I didn't like the food we order.", "I didn't like the food where we ordered."] },
  dnd_l3_9: { full: "My grandmother, who is 85, can not swim.",
    pos: ["My grandma, who is 85 years old, cannot swim.", "My grandmother, who is 85, can't swim.", "My gran, who is eighty-five, doesn't know how to swim."],
    neg: ["My grandmother, that is 85, can't swim.", "My grandmother, which is 85, can't swim.", "My grandmother, who has 85 years, can't swim.",
          "My grandmother, is 85, can't swim.", "My grandmother, who is 85, can't to swim.", "My grandmother, who is 85, doesn't can swim.", "My grandmother, who is 85, can't swimming."] },

  /* ---------- 5 · Prepositions, whom & quantifiers ---------- */
  prep_l3_0: { full: "The girl I spoke to is very nice.",
    pos: ["The girl who I talked to is really friendly.", "The girl to whom I spoke is very nice.", "The girl that I spoke to is very kind.", "The girl with whom I spoke is very nice."],
    neg: ["The girl to who I spoke is very nice.", "The girl to that I spoke is very nice.", "The girl I spoke to her is very nice.", "The girl which I spoke to is very nice.",
          "The girl to whom I spoke to is very nice.", "The girl I spoke is very nice.", "The girl whom I spoke to her is very nice."] },
  prep_l3_1: { full: "I have two cousins, both of whom live in France.",
    pos: ["I've got two cousins, both of whom live in France.", "I have 2 cousins, both of whom live in France."],
    neg: ["I have two cousins, both of who live in France.", "I have two cousins, both of them live in France.", "I have two cousins, both of which live in France.",
          "I have two cousins, both of whom lives in France.", "I have two cousins, both whom live in France.", "I have two cousins, both of whom live on France.",
          "I have two cousins, whom both of live in France."] },
  prep_l3_2: { full: "This is the house in which Goya lived.",
    pos: ["This is the house where Goya lived.", "This is the house Goya lived in.", "This is the house that Goya used to live in.", "This is the house which Goya lived in."],
    neg: ["This is the house in that Goya lived.", "This is the house in where Goya lived.", "This is the house in which Goya lived in.", "This is the house which Goya lived.",
          "This is the house where Goya lived in.", "This is the house in who Goya lived.", "This is the house in which Goya live."] },
  prep_l3_3: { full: "I bought ten books, most of which are novels.",
    pos: ["I bought 10 books, most of which are novels.", "I bought ten books, most of which were novels."],
    neg: ["I bought ten books, most of them are novels.", "I bought ten books, most of that are novels.", "I bought ten books, most of whom are novels.",
          "I bought ten books, most of what are novels.", "I bought ten books, most which are novels.", "I bought ten books, most of which is novels.",
          "I buyed ten books, most of which are novels."] },
  prep_l3_4: { full: "What I need is sleep.",
    pos: ["What I need is to sleep.", "What I need is some sleep."],
    neg: ["That I need is sleep.", "Which I need is sleep.", "The what I need is sleep.", "What I need it is sleep.", "What I need is sleeping.",
          "What need I is sleep.", "What I need are sleep."] },
  prep_l3_5: { full: "Who is the boy you were dancing with?",
    pos: ["Who's the boy that you were dancing with?", "Who is the boy with whom you were dancing?", "Who is the boy who you were dancing with?"],
    neg: ["Who is the boy with who you were dancing?", "Who is the boy with that you were dancing?", "Who is the boy you were dancing with him?",
          "Who is the boy with whom you were dancing with?", "Who is the boy which you were dancing with?", "Who is the boy you were dancing?",
          "Who is the boy you was dancing with?"] },
  prep_l3_6: { full: "Is this the song you told me about?",
    pos: ["Is this the song that you told me about?", "Is this the song about which you told me?", "Is this the song which you talked to me about?"],
    neg: ["Is this the song about that you told me?", "Is this the song you told me about it?", "Is this the song about which you told me about?",
          "Is this the song you told me?", "Is this the song who you told me about?", "Is this the song what you told me about?", "Is this the song you said me about?"] },
  prep_l3_7: { full: "Did you understand what the teacher said?",
    pos: ["did you understand what the teacher said"],
    neg: ["Did you understand that the teacher said?", "Did you understand which the teacher said?", "Did you understood what the teacher said?",
          "Did you understand what said the teacher?", "Did you understand what the teacher say?", "Do you understand what the teacher said?",
          "Did you understand the what the teacher said?"] },
  prep_l3_8: { full: "I do not like the people I work with.",
    pos: ["I don't like the people who I work with.", "I don't like the people with whom I work.", "I don't like the people that I work with."],
    neg: ["I don't like the people with who I work.", "I don't like the people with that I work.", "I don't like the people I work with them.",
          "I don't like the people which I work with.", "I don't like the people I work.", "I don't like the people with whom I work with.",
          "I doesn't like the people I work with."] },
  prep_l3_9: { full: "I invited twenty people, many of whom did not come.",
    pos: ["I invited 20 people, many of whom didn't come.", "I invited twenty people, many of whom didn't turn up."],
    neg: ["I invited twenty people, many of who didn't come.", "I invited twenty people, many of them didn't come.", "I invited twenty people, many of which didn't come.",
          "I invited twenty people, many of whom didn't came.", "I invited twenty people, many whom didn't come.", "I invited twenty people, many of whom don't come.",
          "I invite twenty people, many of whom didn't come."] },

  /* ---------- 6 · Reduced ---------- */
  red_l3_0: { full: "The man sitting on the bench is my uncle.",
    pos: ["the man sitting on the bench is my uncle"],
    neg: ["The man sat on the bench is my uncle.", "The man who sitting on the bench is my uncle.", "The man sit on the bench is my uncle.", "The man sitting in the bench is my uncle.",
          "The man sitting on the bench are my uncle.", "The man sits on the bench is my uncle.", "The man seated on the bank is my uncle."] },
  red_l3_1: { full: "It is a book written by a twelve-year-old girl.",
    pos: ["It's a book written by a 12-year-old girl.", "This is a book written by a twelve year old girl."],
    neg: ["It is a book wrote by a twelve-year-old girl.", "It is a book writing by a twelve-year-old girl.", "It is a book which written by a twelve-year-old girl.",
          "It is a book written for a twelve-year-old girl.", "It is a book written by a twelve-years-old girl.", "It is a book written by a girl of twelve years old.",
          "Is a book written by a twelve-year-old girl."] },
  red_l3_2: { full: "She was the first person to arrive.",
    pos: ["She was the first one to arrive.", "She was the first person to get there."],
    neg: ["She was the first person arriving.", "She was the first person in arrive.", "She was the first person arrived.", "She was the first person to arrived.",
          "She was the first person who arrive.", "She is the first person to arrive.", "She was first person to arrive."] },
  red_l3_3: { full: "The cars made in Zaragoza are exported all over Europe.",
    pos: ["Cars made in Zaragoza are exported to all of Europe.", "The cars manufactured in Zaragoza are exported throughout Europe.", "The cars produced in Zaragoza are exported across Europe."],
    neg: ["The cars making in Zaragoza are exported all over Europe.", "The cars which made in Zaragoza are exported all over Europe.", "The cars made in Zaragoza export all over Europe.",
          "The cars made in Zaragoza are export all over Europe.", "The cars made in Zaragoza is exported all over Europe.", "The cars maked in Zaragoza are exported all over Europe.",
          "The cars made on Zaragoza are exported all over Europe."] },
  red_l3_4: { full: "The girl wearing glasses is my sister.",
    pos: ["the girl wearing glasses is my sister!"],
    neg: ["The girl who wearing glasses is my sister.", "The girl wears glasses is my sister.", "The girl worn glasses is my sister.", "The girl wearing glasses are my sister.",
          "The girl carrying glasses is my sister.", "The girl wearing glass is my sister.", "The girl wear glasses is my sister."] },
  red_l3_5: { full: "Who is the boy talking to Ana?",
    pos: ["Who's the boy talking with Ana?", "Who is the boy speaking to Ana?"],
    neg: ["Who is the boy talks to Ana?", "Who is the boy who talking to Ana?", "Who is the boy talked to Ana?", "Who is the boy talking Ana?",
          "Who the boy is talking to Ana?", "Who are the boy talking to Ana?", "Who is the boy talking at Ana?"] },
  red_l3_6: { full: "Have you seen the photo taken by my father?",
    pos: ["Have you seen the picture taken by my dad?", "Did you see the photo taken by my father?", "Have you seen the photograph taken by my father?"],
    neg: ["Have you seen the photo took by my father?", "Have you seen the photo taking by my father?", "Have you seen the photo made by my father?",
          "Have you seen the photo which taken by my father?", "Have you saw the photo taken by my father?", "Have you seen the photo taken for my father?",
          "Have you seen the photo taken by my fathers?"] },
  red_l3_7: { full: "Is this the last train to leave for Huesca?",
    pos: ["Is this the last train to go to Huesca?"],
    neg: ["Is this the last train leaving for Huesca?", "Is this the last train to leaves for Huesca?", "Is this the last train left for Huesca?", "Is this the last train to leave to Huesca?",
          "This is the last train to leave for Huesca?", "Is this the last train for leave for Huesca?", "Is this last train to leave for Huesca?"] },
  red_l3_8: { full: "Students arriving late can not come in.",
    pos: ["The students arriving late cannot go in.", "Students arriving late aren't allowed to enter.", "Students arriving late can't get in."],
    neg: ["Students arrived late can't come in.", "Students who arriving late can't come in.", "Students arrive late can't come in.", "Students arriving late can't to come in.",
          "Students arriving late don't can come in.", "Students arriving lately can't come in.", "Students arriving late can't entering."] },
  red_l3_9: { full: "The houses built near the river are not safe.",
    pos: ["The houses built close to the river are not safe.", "Houses built next to the river aren't safe."],
    neg: ["The houses building near the river aren't safe.", "The houses builded near the river aren't safe.", "The houses which built near the river aren't safe.",
          "The houses built near the river isn't safe.", "The houses built near the river aren't secure safe.", "The houses built near of the river aren't safe.",
          "The houses built near the river don't safe."] },

  /* ---------- 7 · Rephrasing ---------- */
  reph_l3_0: { full: "My sister, who lives in Madrid, is a nurse.",
    pos: ["My sister, who is a nurse, lives in Madrid.", "My sister who lives in Madrid is a nurse"],
    neg: ["My sister, that lives in Madrid, is a nurse.", "My sister, who she lives in Madrid, is a nurse.", "My sister is a nurse, who lives in Madrid.",
          "My sister, which lives in Madrid, is a nurse.", "My sister, lives in Madrid, is a nurse.", "My sister, who live in Madrid, is a nurse.",
          "My sister, whose lives in Madrid, is a nurse."] },
  reph_l3_1: { full: "This is the café where we met for the first time.",
    pos: ["This is the cafe where we first met.", "This is the café where we met for the first time"],
    neg: ["This is the café where we met there for the first time.", "This is the café which we met for the first time.", "This is the café that we met for the first time.",
          "This is the café where we first met for the first time.", "This is the café when we met for the first time.", "This is the café where we meet for the first time.",
          "This is the café in which we met for the first time."] },
  reph_l3_2: { full: "I have a friend whose mother is a famous writer.",
    pos: ["I've got a friend whose mum is a famous writer.", "I have got a friend whose mother is a famous writer."],
    neg: ["I have a friend who his mother is a famous writer.", "I have a friend whose his mother is a famous writer.", "I have a friend who's mother is a famous writer.",
          "I have a friend which mother is a famous writer.", "I have a friend whose mother is famous writer.", "I have a friend that his mother is a famous writer.",
          "I have a friend whose mother is a writer famous."] },
  reph_l3_3: { full: "He forgot my birthday, which made me sad.",
    pos: ["He forgot my birthday which made me sad"],
    neg: ["He forgot my birthday, that made me sad.", "He forgot my birthday, what made me sad.", "He forgot my birthday, which this made me sad.",
          "He forgot my birthday, who made me sad.", "He forgot my birthday, which made me to feel sad.", "He forgot my birthday, which make me sad.",
          "He forgotten my birthday, which made me sad."] },
  reph_l3_4: { full: "The film that we watched last night was really scary.",
    pos: ["The movie that we watched last night was really scary."],
    neg: ["The film was really scary that we watched last night.", "The film that we watched it last night was really scary.", "The film which we watched last night was really scary.",
          "The film we watched last night was really scary.", "The film who we watched last night was really scary.", "The film that we watch last night was really scary.",
          "The film that we watched last night were really scary."] },
  reph_l3_5: { full: "Is that the man who stole your bag?",
    pos: ["is that the man who stole your bag"],
    neg: ["Is that the man who he stole your bag?", "Is that the man which stole your bag?", "Is that the man stole your bag?", "Is that the man that stole your bag?",
          "Is that the man who did steal your bag?", "Is that the man whose stole your bag?", "That is the man who stole your bag?"] },
  reph_l3_6: { full: "Do you remember the day when we went to the zoo?",
    pos: ["do you remember the day when we went to the zoo"],
    neg: ["Do you remember the day when we went to the zoo that day?", "Do you remember the day where we went to the zoo?", "Do you remember the day which we went to the zoo?",
          "Do you remember the day we went to the zoo?", "Do you remember the day when we go to the zoo?", "Do you remember the day when we went to zoo?",
          "Do you remember the day when did we go to the zoo?"] },
  reph_l3_7: { full: "Have you seen the photos which I took in Rome?",
    pos: ["have you seen the photos which I took in Rome"],
    neg: ["Have you seen the photos which I took them in Rome?", "Have you seen the photos that I took in Rome?", "Have you seen the photos who I took in Rome?",
          "Have you seen the photos I took in Rome?", "Have you seen the photos which I take in Rome?", "Have you saw the photos which I took in Rome?",
          "Have you seen the photos which I took on Rome?"] },
  reph_l3_8: { full: "I do not know the girl who is sitting next to Pablo.",
    pos: ["I don't know the girl who's sitting next to Pablo.", "I dont know the girl whos sitting next to Pablo"],
    neg: ["I don't know the girl who she is sitting next to Pablo.", "I don't know the girl which is sitting next to Pablo.", "I don't know the girl is sitting next to Pablo.",
          "I don't know the girl that is sitting next to Pablo.", "I don't know the girl who sitting next to Pablo.", "I don't know the girl who is sitting next Pablo.",
          "I don't know the girl who are sitting next to Pablo."] },
  reph_l3_9: { full: "The bus which I was waiting for did not stop.",
    pos: ["The bus for which I was waiting didn't stop."],
    neg: ["The bus which I was waiting for it didn't stop.", "The bus didn't stop which I was waiting for.", "The bus for which I was waiting for didn't stop.",
          "The bus that I was waiting for didn't stop.", "The bus which I was waiting didn't stop.", "The bus which I was waiting for doesn't stop.",
          "The bus who I was waiting for didn't stop."] },

  /* ---------- 8 · Review ---------- */
  review_l3_0: { full: "The boy who lives opposite plays the guitar.",
    pos: ["The boy that lives across the street plays the guitar.", "The boy who lives across the road plays guitar."],
    neg: ["The boy which lives opposite plays the guitar.", "The boy lives opposite plays the guitar.", "The boy who live opposite plays the guitar.",
          "The boy who lives opposite play the guitar.", "The boy who lives opposite touches the guitar.", "The boy who he lives opposite plays the guitar.",
          "The boy whose lives opposite plays the guitar."] },
  review_l3_1: { full: "Zaragoza, where I was born, is a very big city.",
    pos: ["Zaragoza, where I was born, is a really large city.", "Zaragoza, in which I was born, is a very big city."],
    neg: ["Zaragoza, which I was born, is a very big city.", "Zaragoza, that I was born, is a very big city.", "Zaragoza, where I born, is a very big city.",
          "Zaragoza, where I was born in, is a very big city.", "Zaragoza, where I was born, is a very bigger city.", "Zaragoza, where I was born there, is a very big city.",
          "Zaragoza, when I was born, is a very big city."] },
  review_l3_2: { full: "I have a neighbour whose cat is black.",
    pos: ["I've got a neighbor whose cat is black.", "I have got a neighbour whose cat is black."],
    neg: ["I have a neighbour who her cat is black.", "I have a neighbour who's cat is black.", "I have a neighbour which cat is black.", "I have a neighbour whose cat is a black.",
          "I have a neighbour whose her cat is black.", "I have a neighbour that cat is black.", "I have a neighbour whose cat are black."] },
  review_l3_3: { full: "My father, who is a teacher, speaks three languages.",
    pos: ["My dad, who is a teacher, speaks 3 languages."],
    neg: ["My father, that is a teacher, speaks three languages.", "My father, which is a teacher, speaks three languages.", "My father, is a teacher, speaks three languages.",
          "My father, who is teacher, speaks three languages.", "My father, who is a teacher, speak three languages.", "My father, who is a teacher, talks three languages.",
          "My father, whose is a teacher, speaks three languages."] },
  review_l3_4: { full: "I love the song you are listening to.",
    pos: ["I love the song that you're listening to.", "I really like the song which you are listening to."],
    neg: ["I love the song you are listening.", "I love the song you are listening to it.", "I love the song who you are listening to.", "I love the song what you are listening to.",
          "I love the song you are hearing to.", "I love the song you listening to.", "I loves the song you are listening to."] },
  review_l3_5: { full: "Where is the book that was on my desk?",
    pos: ["Where's the book which was on my table?"],
    neg: ["Where is the book who was on my desk?", "Where is the book was on my desk?", "Where is the book that were on my desk?", "Where is the book that it was on my desk?",
          "Where the book is that was on my desk?", "Where is the book what was on my desk?", "Where is the book that was in my desk?"] },
  review_l3_6: { full: "Is that the woman whose son is an actor?",
    pos: ["is that the woman whose son is an actor"],
    neg: ["Is that the woman who her son is an actor?", "Is that the woman who's son is an actor?", "Is that the woman which son is an actor?", "Is that the woman whose son is actor?",
          "Is that the woman whose her son is an actor?", "That is the woman whose son is an actor?", "Is that the woman whose son is a actor?"] },
  review_l3_7: { full: "Did you like the cake my mother made?",
    pos: ["Did you like the cake that my mum made?", "Did you like the cake which my mother baked?"],
    neg: ["Did you like the cake who my mother made?", "Did you like the cake my mother made it?", "Did you like the cake what my mother made?", "Did you liked the cake my mother made?",
          "Did you like the cake my mother did?", "Did you like the cake my mother make?", "Do you liked the cake my mother made?"] },
  review_l3_8: { full: "I do not know what you want.",
    pos: ["I don't know what you want.", "I dont know what you want"],
    neg: ["I don't know that you want.", "I don't know which you want.", "I don't know what do you want.", "I don't know what you wants.", "I not know what you want.",
          "I doesn't know what you want.", "I don't know the what you want."] },
  review_l3_9: { full: "I did not like the hotel where we stayed.",
    pos: ["I didn't like the hotel we stayed at.", "I did not like the hotel that we stayed in.", "I didn't like the hotel in which we stayed."],
    neg: ["I didn't like the hotel where we stayed at.", "I didn't like the hotel which we stayed.", "I didn't like the hotel who we stayed.", "I didn't like the hotel where we stayed in.",
          "I didn't liked the hotel where we stayed.", "I didn't like the hotel where we stay.", "I didn't like the hotel when we stayed."] }
};
